---

services:
  api:
    build:
      dockerfile: api/container/Containerfile
      context: .
      target: prod
    ports:
      - "8080:8000"
    environment:
      - DYNAMODB_ENDPOINT=http://db:8000
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

volumes:
  dynamodb: